version: '1.0.{build}'

image: ubuntu

matrix:
  fast_finish: true

configuration:
  - Debug
  - Release

install:
  # Ubuntu 16.04 (required for cleaning: 18.04)
  - lsb_release -a
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y

  # gcc 8
  - sudo apt-get update -y
  - sudo apt-get install gcc-8 g++-8 -y
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8
  # Selected automatically as there's no alternative
  # - sudo update-alternatives --config gcc
  # - select gcc-8

before_build:
  - ldd --version
  - g++ -v
  - env
  
  # Appveyor limitation
  - git submodule update --init --recursive
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=${CONFIGURATION} ..

build_script:
  - make -j8 VERBOSE=1

test_script:
  - ./bin/test_${APPVEYOR_PROJECT_NAME}
  - if [ "${CONFIGURATION}" = "Release" ]; then
      ./bin/benchmark_${APPVEYOR_PROJECT_NAME}
    fi
