version: '1.0.{build}'

image: ubuntu

matrix:
  fast_finish: true

configuration:
  - Debug
  - Release

build: off
test: off

install:
  - lsb_release -a
  - ls -al

  # Remove once appveyor move to Ubuntu 18.04
  - sudo apt-get update -y
  - sudo apt-get upgrade -y
  - sudo apt-get dist-upgrade -y
  - sudo apt-get install build-essential software-properties-common -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y

  # gcc 8
  - sudo apt-get update -y
  - sudo apt-get install gcc-8 g++-8 -y
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8

  - sudo update-alternatives --config gcc
  - select gcc-8

  - ldd --version
  - g++ -v

  - mkdir build && cd build
  - cmake -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_BUILD_TYPE=Release -DTRAVIS_BUILD=ON ..
  - make -j8 VERBOSE=1
