version: '1.0.{build}'

image: ubuntu

matrix:
  fast_finish: true

configuration:
  - Debug
  - Release

environment:
  UPDATE_ALTERNATIVE_PRIORITY: 9999

  matrix:
    - COMPILER: gcc
      COMPILER_CPP: g++
      COMPILER_VERSION: 8

    - COMPILER: clang
      COMPILER_CPP: clang++
      COMPILER_VERSION: 6.0

install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -y
  - sudo apt-get install ${COMPILER}-${COMPILER_VERSION} ${COMPILER_CPP}-${COMPILER_VERSION} -y
  - sudo update-alternatives --install /usr/bin/${COMPILER} ${COMPILER} /usr/bin/${COMPILER}-${COMPILER_VERSION} ${UPDATE_ALTERNATIVE_PRIORITY} --slave /usr/bin/${COMPILER_CPP} ${COMPILER_CPP} /usr/bin/${COMPILER_CPP}-${COMPILER_VERSION}
  - sudo apt-get install cppcheck -y

before_build:
  # Debug logs
  - lsb_release -a
  - ldd --version
  - ${COMPILER_CPP} -v
  - cppcheck --version
  - env

  # Appveyor limitation
  - git submodule update --init --recursive
  - mkdir build && cd build
  - cmake -DCMAKE_CXX_COMPILER=/usr/bin/${COMPILER_CPP} -DCMAKE_BUILD_TYPE=${CONFIGURATION} ..

build_script:
  - make -j8 VERBOSE=1

after_build:
  # Cannot activate --error-exitcode=1 as there's false positive (16.04)
  - cppcheck --enable=all --inline-suppr --suppress=missingIncludeSystem ${APPVEYOR_BUILD_FOLDER}/${APPVEYOR_PROJECT_NAME}/

test_script:
  - ctest -V

after_test:
  - if [ "${CONFIGURATION}" = "Release" ]; then
      ./bin/benchmark_${APPVEYOR_PROJECT_NAME};
    fi

# - TODO:
# lto release
# add benchmark from the presentation
# report cppcheck
# report test
# report benchmark + graph
