version: '1.0.{build}'

image: ubuntu

matrix:
  fast_finish: true

configuration:
  - Debug
  - Release

environment:
  GCC_MAJOR_VERSION_TARGET: 8
  UPDATE_ALTERNATIVE_PRIORITY: 9999

install:
  # Ubuntu 16.04 (required for cleaning: 18.04)
  - lsb_release -a
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -y
  - sudo apt-get install gcc-${GCC_MAJOR_VERSION_TARGET} g++-${GCC_MAJOR_VERSION_TARGET} -y
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${GCC_MAJOR_VERSION_TARGET} ${UPDATE_ALTERNATIVE_PRIORITY} --slave /usr/bin/g++ g++ /usr/bin/g++-${GCC_MAJOR_VERSION_TARGET}
  # Selected automatically as there's no alternative
  # - sudo update-alternatives --config gcc
  # - select gcc-8

before_build:
  - ldd --version
  - g++ -v
  - env

  # Appveyor limitation
  - git submodule update --init --recursive
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=${CONFIGURATION} ..

build_script:
  - make -j8 VERBOSE=1

test_script:
  - ./bin/test_${APPVEYOR_PROJECT_NAME}
  - if [ "${CONFIGURATION}" = "Release" ]; then
      ./bin/benchmark_${APPVEYOR_PROJECT_NAME};
    fi
