version: '1.0.{build}'

image: ubuntu

matrix:
  fast_finish: true

configuration:
  - Debug
  - Release

build: off
test: off

install:
  # Ubuntu 16.04 (required for cleaning: 18.04)
  - lsb_release -a

  # Remove once appveyor move to the required version
  # Break appveyor (anyway, it's too slow and not needed)
  # - sudo apt-get update -y
  # - sudo apt-get upgrade -y
  # - sudo apt-get dist-upgrade -y
  # - sudo apt-get install build-essential software-properties-common -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y

  # gcc 8
  - sudo apt-get update -y
  - sudo apt-get install gcc-8 g++-8 -y
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8

  # Selected automatically as there's no alternative
  # - sudo update-alternatives --config gcc
  # - select gcc-8

  - ldd --version
  - g++ -v
  # Debug
  - env

  # Appveyor limitation
  - git submodule update --init --recursive
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=${CONFIGURATION} ..
  - make -j8 VERBOSE=1
