version: '1.0.{build}'

image: ubuntu

matrix:
  fast_finish: true

configuration:
  - Debug
  - Release

environment:
  CLANG_VERSION: 6.0
  CPP_CHECK_OUTPUT_FILE: cppcheck_output.xml
  GTEST_OUTPUT_FILE: gtest_output.xml
  GOOGLEBENCHMARK_OUTPUT_FILE: googlebenchmark_output.csv
  LCOV_OUTPUT_FILE: lcov.info
  LCOV_TEST_DIRECTORY: experimental/tests/CMakeFiles/test_experimental.dir/tests
  PYTHON_MAJOR_VERSION: 3
  UPDATE_ALTERNATIVE_PRIORITY: 9999

  matrix:
    - COMPILER: gcc
      COMPILER_CPP: g++
      COMPILER_VERSION: 8

    - COMPILER: clang
      COMPILER_CPP: clang++
      COMPILER_VERSION: ${CLANG_VERSION}

install:
  # Compilers
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -y
  - sudo apt-get install ${COMPILER}-${COMPILER_VERSION} ${COMPILER_CPP}-${COMPILER_VERSION} -y
  - sudo update-alternatives --install /usr/bin/${COMPILER} ${COMPILER} /usr/bin/${COMPILER}-${COMPILER_VERSION} ${UPDATE_ALTERNATIVE_PRIORITY} --slave /usr/bin/${COMPILER_CPP} ${COMPILER_CPP} /usr/bin/${COMPILER_CPP}-${COMPILER_VERSION}

  # Python
  - sudo apt-get install python${PYTHON_MAJOR_VERSION}-pip -y
  - pip${PYTHON_MAJOR_VERSION} install pandas
  - pip${PYTHON_MAJOR_VERSION} install matplotlib

  # Coverage
  - |
    if [ "gcc" == "${COMPILER}" ]; then
      git clone https://github.com/linux-test-project/lcov.git
      cd lcov && sudo make install && cd .. && rm -rf lcov
    fi

  # Static analysis
  - sudo apt-get install cppcheck -y
  - sudo apt-get install clang-tidy-${CLANG_VERSION} -y
  - sudo ln -s  /usr/bin/clang-tidy-${CLANG_VERSION} /usr/bin/clang-tidy
  - sudo apt-get install clang-format-${CLANG_VERSION} -y
  - sudo ln -s  /usr/bin/clang-format-${CLANG_VERSION} /usr/bin/clang-format

  - appveyor AddMessage 'Install succeed!' -Category Information

before_build:
  # Debug logs
  - lsb_release -a
  - ldd --version
  - ld -v
  - ${COMPILER_CPP} -v
  - cmake --version
  - cppcheck --version
  - env

  # cmake
  - git submodule update --init --recursive
  - mkdir build && cd build
  - export GTEST_OUTPUT="xml:${PWD}/${GTEST_OUTPUT_FILE}"
  - cmake -DCMAKE_CXX_COMPILER=/usr/bin/${COMPILER_CPP} -DCMAKE_BUILD_TYPE=${CONFIGURATION} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..

build_script:
  - make -j8 VERBOSE=1
  - appveyor AddMessage 'Build succeed!' -Category Information

after_build:
  - make cppcheck-deprecated 2> ${PWD}/${CPP_CHECK_OUTPUT_FILE}
  - appveyor PushArtifact ${PWD}/${CPP_CHECK_OUTPUT_FILE}

  - |
    make clang-format-xml | grep "<replacement "

    if [ 1 -ne $? ]; then
      echo "Formatting change required by clang-format!"
      exit 1
    fi

  - |
    if [ "clang" == "${COMPILER}" ]; then
      make clang-tidy &> clang-tidy_output.log
      appveyor PushArtifact ${PWD}/clang-tidy_output.log
    fi

  - appveyor AddMessage 'Static analysis succeed!' -Category Information

test_script:
  - ctest -V

  - python3 ../appveyor/upload_gtest_result.py --gtest_xml=${PWD}/${GTEST_OUTPUT_FILE}
  - appveyor PushArtifact ${PWD}/${GTEST_OUTPUT_FILE}
  - appveyor AddMessage 'Tests succeed!' -Category Information

after_test:
  # Coverage
  - |
    if [ "Debug" == "${CONFIGURATION}" ]; then
      if [ "gcc" == "${COMPILER}" ]; then
        lcov --gcov-tool /usr/bin/gcov-${COMPILER_VERSION} -c -d ${PWD}/${LCOV_TEST_DIRECTORY}/ -o ${LCOV_OUTPUT_FILE}
        lcov --gcov-tool /usr/bin/gcov-${COMPILER_VERSION} --remove ${LCOV_OUTPUT_FILE} '/usr/include/*' '*/external/*' -o ${LCOV_OUTPUT_FILE}

        mkdir gcov_report
        genhtml ${LCOV_OUTPUT_FILE} -o ${PWD}/gcov_report/
        zip -r gcov_report.zip gcov_report/

        appveyor PushArtifact gcov_report.zip
      elif [ "clang" == "${COMPILER}" ]; then
        llvm-profdata-${CLANG_VERSION} merge -output=llvm-cov.profdata ${PWD}/experimental/tests/default.profraw
        llvm-cov-${CLANG_VERSION} show -format=html -instr-profile=llvm-cov.profdata ./bin/test_experimental > llvm-cov_report.html
        zip llvm-cov_report.zip llvm-cov_report.html

        appveyor PushArtifact ${PWD}/llvm-cov_report.zip
      fi
    fi

  # Benchmark
  - |
    if [ "Release" == "${CONFIGURATION}" ]; then
      ./bin/benchmark_${APPVEYOR_PROJECT_NAME} --benchmark_out=${PWD}/${GOOGLEBENCHMARK_OUTPUT_FILE} --benchmark_out_format=csv

      python3 ../appveyor/upload_googlebenchmark_result.py --googlebenchmark_csv=${PWD}/${GOOGLEBENCHMARK_OUTPUT_FILE}
      appveyor PushArtifact ${PWD}/${GOOGLEBENCHMARK_OUTPUT_FILE}
      appveyor AddMessage 'Benchmark succeed!' -Category Information
    fi

# - TODO:
# add benchmark from the presentation
# lto release (on hold until 18.04 release on appveyor)
